### ISSUE TITLE
Milestone Planning

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#116]
```[tasklist]
### Tasks
- [x] Outline agenda and prep materials - by EOD Friday
- [x] Host a discussion amongst the team (scheduled Tuesday 8/1)
- [x] Transcribe into Project Phase
- [x] Transcribe Now/Next/Later priorities into Roadmap and Opportunity Tree
```
