### ISSUE TITLE
Stand up traditional Drupal as control

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#120]
### Description
CMS prototyping scope is listed in our [CMS strategy doc](https://docs.google.com/document/d/1sgsPErrR_HtVfljt7EK5fWMA8p9f2vKnn4GkRjRfboA/edit#heading=h.ljvidygtuupa).

**Related Epic: [#Epic]**

### Acceptance Criteria
- [x] We have an HTML theme for dynamic data (used for all CMS)
- [x] We install the HTML theme as a Drupal theme
- [x] We test static, dynamic, ingested, and conditional data components on a page
- [ ] We build a dashboard of location related content
- [ ] We demonstrate publishing workflow
- [ ] FInishing the feature list for Drupal
- [ ] Handling dependencies (discuss at Eng sync today 8/21)

```[tasklist]
### Tasks
- [ ] 
```

**Comment by colinmurphy01** [comment]
Not blocked by #133

**Comment by mgwalker** [comment]
I'm going to write up some of the stuff I think we'll need to resolve. I suspect these are mostly going to be true regardless of the CMS we pick, but I've only been using Drupal for all the infrastructure prototyping, so that's the one these questions are coming from.

1. **How do we package modules, themes, and other plugins with the CMS for deployment?**  
   I feel like the best option is to store plugin code ourselves and use that to build a custom container. That gives us more control over versioning at the cost of a slightly more complex repo and a more complex deployment process. But I don't think either of those are *significantly* more complex

   Another option would be to store the plugins in an external filesystem shared into the container. This is how the prototype infrastructure is configured. Where I'm uncertain here is how the plugins get into the external filesystem. Do we keep a separate repo of plugins and have a separate deployment process for those? (That seems more complex than the previous option.) Do we... manually load them onto the filesystem? That's just begging for disaster, I think.

2. **How do we *enable* installed modules?**  
   Drupal recognizes plugins by seeing them on the filesystem when it starts up. I assume it is a similar story for WordPress and other CMSes. However, Drupal does not enable those modules by default. They are enabled in the UI, and that gets saved to Drupal's configuration in the backing database. @cannandev has pointed to default configuration files that allow plugins to install themselves, and that's probably the way we want to go if we can. One benefit is it's a necessary enabler for standing up a new instance of the site elsewhere where everything is identical except the content. Another is that we can version-control that default configuration.

3. **Can we version-control CMS configuration?**  
    Drupal's configuration is stored mostly in the database, which might make it difficult to version control. If the only configuration we need to keep is with the modules and we can define module default configurations via config files, that seems to solve the problem. But if there are configuration changes that are only made in the UI, how do we capture those as a moment-in-time, and how do we play those back later? How do we instantiate a new instance of the site in a different environment and have it be identical (sans content)? If we deploy something that breaks, how do we roll the configuration back to a known-good state in a repeatable, automatable way?

I've been fiddling with these questions and I don't really have answers to any of them, just hypotheses. We can revisit those hypotheses later once we've picked a CMS, but I wanted to record these questions now, while they're still in my head and before I close all the open browser tabs where I'm trying to get answers. 😂

**Comment by mgwalker** [comment]
ii. and iii. above are resolved! Claire got the configuration export working in #141 and we worked that into our dev Docker configuration in #143. The way we handle configuration in dev is indicative of how we can do it in production.

Remains to be seen whether the same solutions apply to WordPress, but that's what #121 is for. 😄

**Comment by colinmurphy01** [comment]
I believe this can be closed.
