### ISSUE TITLE
CI/CD proposal

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#124]
```[tasklist]
### Tasks
- [ ] Discuss with Andrew and Warrick about CI/CD tooling and Fisma considerations
- [ ] Draft a diagram of components
- [ ] Conduct further research
- [ ] Share with Andrew and Warrick for feedback
- [ ] Share with core team for feedback
```

**Comment by loganmeetsworld** [comment]
beginnings of a diagram from conversations yesterday: 

![weather gov deployment](https://github.com/18F/weather.gov/assets/10510566/76ca859f-7dfe-445e-bb74-074fddc0640d)

**Comment by colinmurphy01** [comment]
I'm sorry Logan. I forgot about #98. I suggest you migrate your work to that ticket and we close this one because that will be our ADR - unless you like keeping them separate?
