### ISSUE TITLE
Finalize FISMA level and understand what that means for our architecture choices

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#126]
```[tasklist]
### Tasks
- [ ] understand what is needed here - current weather.gov is moderate
- [ ] Set availability standards
- [ ] Review current approved software list for agency
- [ ] Identify a System Owner
```

**Comment by colinmurphy01** [comment]
Related ticket #35, consider merging.

**Comment by loganmeetsworld** [comment]
I prefer #35! Will assign to me.
