### ISSUE TITLE
Stand up a Drupal instance in Docker

### ISSUE THREAD

**Issue by mgwalker** [18F/weather.gov#19]
Prototyping the technical requirements for running Drupal in a containerized environment. We want to understand mapping out external connections and injecting custom templates, etc.
```[tasklist]
### Tasks
```

**Comment by mgwalker** [comment]
Update: Got Drupal running. That part was easier than expected. Next up Claire and I will be pairing to work out how to get custom templates, etc. into the container. Probably just need to map a volume, but we'll see when we play with it!

**Comment by cannandev** [comment]
We've figured it out! We had to [bind mount](https://docs.docker.com/storage/bind-mounts/) the themes directory from the docker-compose.yml file. There's a new branch called `hello-world-drupal-theme`.

**Comment by cannandev** [comment]
@mgwalker Whaddya think for the following tasks as acceptance criteria for this ticket?

- [ ] Get Drupal 10 running
- [ ] Get custom templates into the container
- [ ] CI/CD GitHub deployment for a preview URL
- [ ] Run basic test (pa11y CodeSniffer?)
