### ISSUE TITLE
Identify our outreach strategy and path to PRA approval

### ISSUE THREAD

**Issue by sarahmhgov** [18F/weather.gov#25]
### Background
We'll need to recruit public and partner users for usability testing, once we have wireframes ready. 

Once we develop an outreach strategy (and have PRA approval), we'll prep outreach materials and conduct outreach. [future rocks]

### Questions to consider

- [ ] Who do we have and who do we need
- [ ] What's our sourcing strategy (should we target Nashville or across US) for this phase
- [ ] How will we reach out and recruit (within PRA)
- [ ] What info do we need
- [ ] Do we have PRA approval

```[tasklist]
### Tasks
- [x] Refine [the WFO Involvement Doc](https://docs.google.com/document/d/1Se83xuOdbfJaJMqyf2uSdnV6Uh5Kn-GEwEgse1BM6vk/edit#heading=h.ibkm6nzh0ki6) to set expectations for Nashvile WFO and recruit internal users for prototyping
- [x] Document user types and personnas
- [x] Identify screening criteria
- [x] Identify strategies for recruitment (short-term within Nashville, long-term)
- [x] Prep for a NOAA PRA convo to propose and discuss various strategies
- [x] Kickoff discussion with Tyra Harris
- [x] Documented: Definitions, Screener
- [x] Discuss/Align with team on Screener
- [x] Blurb
- [ ] Emailed blurbs to people we've spoken to
- [x] BONUS: Submitted PRA approval (if applicable)
```

**Comment by colinmurphy01** [comment]
For this sprint:

- [ ] Refine what we think our gaps are in user research
- [ ] Prioritize some initial strategies for recruitment (snowball recruiting)
- [ ] Identify longer-term strategies for recruitment
- [ ] Prep for a NOAA PRA convo to propose and discuss various strategies
- [ ] Kickoff discussion with Tyra Harris

Strategy is once we identify a WFO, we can identify user base through them. 

Blockers for consideration
- PRA Approval
- Screener

**Comment by colinmurphy01** [comment]
@sarahmhgov updated task list based on our convo to reflect the work identified for this sprint.

**Comment by colinmurphy01** [comment]
@sarahmhgov I think you're moving on this. Can you update this before Planning today?

**Comment by colinmurphy01** [comment]
rewriting this ticket to be scoped to this sprint. 

Making the original DEIA recruitment ticket more of a "boulder" sized initiative since this will likely span over multiple sprints.

**Comment by colinmurphy01** [comment]
I know you're balancing a lot but is there a separate doc for the WRN screener, which will likely be much simpler?

**Comment by colinmurphy01** [comment]
this can be closed since we know our outreach stategy and we're waiting on PRA approval
