### ISSUE TITLE
Onboard new team members and re-charter

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#38]
### Background
We have 2 new 18F team members joining and we're kicking off a long-term prototype and build phase for the work within our core team. 

### Acceptance Criteria
- [x] 18F team members are up to speed on what we've done in the PA
- [x] 18F team members have the necessary access they need
- [x] Core team has agreed to a clear list of working agreements
- [x] Core team has agreed to a clear "sweet spot" for scheduling and agreements
- [x] Core team has agreed to a set of tools and means to communicate
- [x] Core team has agreed to methods for decision making

```[tasklist]
### Tasks
- [ ] #30
- [ ] https://github.com/18F/weather.gov/issues/42
- [x] Meet 1:1 with Stacy and Janel to get their additions to an internal charter
- [x] Read out changes to internal charter
- [x] Set up time to swarm on charter within Core Team
- [x] Document and synthesize weahter.gov 2.0 core team charter
- [x] Get explicit agreement and commitment from everyone
```

**Comment by colinmurphy01** [comment]
Public [Weather.gov 2.0 Charter](https://docs.google.com/document/d/1Gmsf9Day4jfQpDHoi28vz63F_l4JNw_fGr-1XJXTbgs/edit#heading=h.obadzxp7l2g2)

**Comment by colinmurphy01** [comment]
Amending our [18F Internal Charter](https://docs.google.com/document/d/1j1AXH6qpB5nzzSPxodT2TrrP2Y2Sm9XC93yYInhIubY/edit) with new team members

**Comment by colinmurphy01** [comment]
Chartering meetings scheduled for Thursday 6/22, 12-1pm EST, 3-4pm EST
