### ISSUE TITLE
Prep PRA submission and user outreach materials

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#72]
### Description
Once #25 is completed, we are now ready to submit for PRA approval and prep outreach materials.

When this is completed, we will be ready to conduct outreach [ticket TBD]. 

```[tasklist]
### Tasks
- [ ] https://github.com/18F/weather.gov/issues/78
- [x] Send screeners to Adrienne, Monica, Valerie, Tyra for review/approval
- [x] Fill out PRA submission forms
- [x] PRA submitted
- [x] WRN Outreach materials drafted
- [x] Spreadsheet is prepared for candidate responses
- [ ] WRN Outreach materials sent to Doug and ready to be sent out
```

**Comment by colinmurphy01** [comment]
Sarah will set up time to rework 1 question in screener, WRN ask.
Colin can take on project management stuff

**Comment by colinmurphy01** [comment]
Now, the generic clearance submission form (attached) must be completed and returned to the NOAA PRA Office.  I can complete the Cost to the Federal Government as well as the Required Additional Information.  Also attached is an example of a completed submission form so you can get an idea of what is needed.


[Generic Clearance  Meetings Events Registrations Etc Submission Template FINAL 2023.docx](https://github.com/18F/weather.gov/files/12264560/Generic.Clearance.Meetings.Events.Registrations.Etc.Submission.Template.FINAL.2023.docx)
[0690-0038 Marine Debris Program Grant Webinar.docx](https://github.com/18F/weather.gov/files/12264559/0690-0038.Marine.Debris.Program.Grant.Webinar.docx)

**Comment by colinmurphy01** [comment]
I think this prep work can be called done.
