### ISSUE TITLE
Align on how weather.gov current defines location and how might we define location?

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#90]
### Description
We know coming out of PA that people use location as a primary means to look up weather information and to verify that the weather conditions relate to them. 

[Survey](https://drive.google.com/drive/folders/1nNOxejenzWOqYAMesNh8A8MOlHHVsyjQ)(page 24)
Current location weather is important for both the Gen Pop and Partners; however, on the main page and in some cases
even after entering a specific location, the most prominent information on the page is regional/national. Current location
information is not prioritized in the content hierarchy.

For partners, "my location" correlates to the area they cover. So if a person is in charge of state emergency services - their location covers the entire state.

**Related Epic: #97 **

```[tasklist]
### Tasks
- [x] Map out current flow from search with location to forecast page
- [x] Discuss as a team what the current state is, map that out
- [ ] Discuss as a team how might we do it in the future, map that out
- [x] Identify constraints or dependencies
- [ ] Success = we can begin design on a location-based component
```

### Hypothesis
City/state is a sufficient starting place for prototype, as most/all locations can be traced to this in some way, and it is more likely to be known by those not local to the area. Zip code could then be included as an iterative improvement for MVP. 
The scaling could look something like: 
City > county > WFO > state > region > national 

Additional research is needed to best understand how to incorporate the less common or less accessible use cases of zip code, lat/long, zone, event area, as well as edge cases where city/zip is less easily translatable to an area where local weather applies. For users who allow the location of their device to be used, we could start with lat/long to map to their specific location, but present it in terms of city/state in the UI. 

Research detailed [in this document](https://docs.google.com/document/d/1ELDm59BWbiJeXz6t9IF8ulLVVaDeH9cSfUdTRRM3SRQ/edit?usp=sharing) 

### Questions remaining
- User research
  - How does a general population user define their location?
  - How do people use zip, city, lat/long to qualify their location, especially for weather information?
  - Use case for consideration: Zip codes are massive in the west (ZIP code 99734 covers 30,000 square miles), not the best definition for my location. What if you're between cities?
- Technical research
  - How does the API map observation data to locations? #84 
  - Location is continuous, how do we map continuous location to a distinct location on the web (is WFO grid right?) should we map lat/long to UTM?
 
### What else is happening around NOAA that will impact this
- Shift away from zone-based forecasts

**Comment by elijah-wright** [comment]
so I'm not a part of 18F or this project, but I did see it and tested out what was here. I noticed that what's being returned by api.weather.gov isn't close to where I live. I saw the name of the city and I didn't even know where that was, but apparently it's miles away. I read up on the weather.gov API and it seems like this is because the 2.5km grid doesn't fit nicely within my area. so if it's possible, maybe the API could return the proper city at least. something within the second or third degree of the latitude/longitude should be ok.

**Comment by colinmurphy01** [comment]
Appreciate the comment @elijah-wright

**Comment by elijah-wright** [comment]
@mgwalker yeah, I do happen to live in the Southwest. I know it's something that the NOAA would need to fix but maybe the API could return the right city, even if the sensor may be miles away?

**Comment by mgwalker** [comment]
Oooh, I think I get it now. The sensor is in location X and you're in city Y. You'd like the API to include "city Y" in the response?

If that's what you mean, then yeah, I agree! Otherwise it looks like it's giving you the wrong data. IMO we'd still need to identify the physical location of the sensor as well, but maybe instead of just telling you the sensor location name, we could also tell you how far away it is. Anyway...

Thanks for responding! This is really helpful!

**Comment by elijah-wright** [comment]
it might be helpful to have an icon with a tooltip or something clarifying where the data is coming from with the city too

**Comment by kmranjo** [comment]
Oh I added it under the hypothesis section, but it does kind of get lost in all the text. [Here is the link](https://docs.google.com/document/d/1ELDm59BWbiJeXz6t9IF8ulLVVaDeH9cSfUdTRRM3SRQ/edit?usp=sharing)

**Comment by colinmurphy01** [comment]
With the hypothesis section and the share out I believe we can call this done. Then as we design/build out the search experience we will use this research as the foundation for that exploration.
