### ISSUE TITLE
Conduct market analysis and make recommendations for a CI/CD pipeline

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#92]
### Description
In order to continuously support a new weather.gov we need to be able to automatically run tests and deploy without human intervention in a way that does not interfere with the continuous operation of the site and maintain compliance and code standards.

The water.weather.gov team is also working on defining their CI/CD pipeline.

**Related Epic: **

### Questions to answer
- [x] What options are in the market?
- [x] Which options best meet our criteria for example
  - What code repositories can it hook up to? And how?
  - How does it manage secrets?
  - How do you create test runners?
- [x] What are the licensing costs, if any?
- [x] Does NWS or NOAA have existing vendor support or experience with these tools?
- [x] How will it fit within a FISMA High system?
- [x] What is our primary recommendation for CI/CD pipeline?

```[tasklist]
### Tasks
- [ ] https://github.com/18F/weather.gov/issues/114
- [ ] https://github.com/18F/weather.gov/issues/115
- [ ] #98
- [ ] https://github.com/18F/weather.gov/issues/133
- [ ] Decide how we use terraform or an alternative
- [ ] Document how we've set up AWS in code
```

**Comment by colinmurphy01** [comment]
Prioritize first 2 tasks into this sprint.

**Comment by colinmurphy01** [comment]
Discussed in backlog refinement today

- [ ] Note to the WOC - preferred tools? @mgwalker will you be doing this?
- [ ] Summarize rec and preview with Kolly

**Comment by mgwalker** [comment]
Sure

**Comment by colinmurphy01** [comment]
Cleaned up to-do list and co-assigned to @loganmeetsworld

**Comment by loganmeetsworld** [comment]
Now that we have a proposed set of tools, I plan to discuss this more in compliance sync this week, but are there others to share our ADR with @mgwalker ?

**Comment by mgwalker** [comment]
It seems like an ADR that will need NWS engineering review, but that can happen after we draft and agree to it internally. We should check with Kari. I feel like if things go well in the compliance sync, we're probably fine to just accept it and then circulate it for visibility rather than for approval.

**Comment by loganmeetsworld** [comment]
I will have the ADR complete for compliance sync then.

**Comment by loganmeetsworld** [comment]
The ADR is complete and I will present our diagram, findings, and ADR at compliance sync.
